apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: gcr.io/seu-projeto/cloudmarket-product:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: cloudmarket-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gcr.io/seu-projeto/cloudmarket-user:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: cloudmarket-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: gcr.io/seu-projeto/cloudmarket-order:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: cloudmarket-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: gcr.io/seu-projeto/cloudmarket-gateway:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: cloudmarket-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/seu-projeto/cloudmarket-frontend:latest
        ports:
        - containerPort: 80
